### ISSUE TITLE
Problems when creating a Payment: "Invalid Credentials"

### ISSUE THREAD

**Issue by RonaldoMoraes** [mercadopago/dx-php#81]
I'm developing an integration with MercadoPago in sandbox mode. When I try to create a payment, I'm always getting "Invalid Credentials":

```
{
    "message": "Invalid credentials",
    "error": "bad_request",
    "status": 400,
    "cause": [
        {
            "code": 17,
            "description": "Invalid credentials",
            "data": null
        }
    ]
}
```

 for the following set of data:

```
public function creditCard($data)
    {
        MercadoPago\SDK::setAccessToken("TEST-6363002050898251-102616-1d91cfca2d92ad4361d0a9ea12043a1d-148760055");
        MercadoPago\SDK::setClientId("6363002050898251");

        $payment = new MercadoPago\Payment();
        $payment->transaction_amount = 15;
        $payment->token = "a95fd09d19e87855ca328598ecad15a2";
        $payment->description = "Ergonomic Silk Shirt";
        $payment->installments = 1;
        $payment->payment_method_id = "visa";

        $payer = new MercadoPago\Payer();
        $payer->email = "test_user_76610919@test.com";
        $payment->payer = $payer;

        dd($payment->save());

        // return $payment->status;
    }
```

And I'm getting the same error even when posting direct to API, via postman, without using the SDK:
![image](https://user-images.githubusercontent.com/4603662/48131192-5da65400-e276-11e8-9773-893be43fa99c.png)

My methods to generate the card token returned:

```
card_number_length: 16
cardholder:
   identification:
      number: "113926846"
      type: "Otro"
   name: "Ronaldera da Bahia"
date_created: "2018-11-07T08:20:34.000-04:00"
date_due: "2018-11-15T08:20:34.000-04:00"
date_last_updated: "2018-11-07T08:20:37.009-04:00"
expiration_month: 8
expiration_year: 2022
first_six_digits: "430568"
id: "5c12b38707abf0ea0888b28e7b73b97d"
last_four_digits: "2314"
live_mode: false
luhn_validation: true
public_key: "TEST-98638d24-eb00-4dd5-82d8-4e573fac6a80"
require_esc: false
security_code_length: 3
status: "active"
```

Can anyone help me? I don't know what I'm missing here..
